### ISSUE TITLE
uvpspec.combine_uvpspec taking very long

### ISSUE THREAD

**Issue by duncanjmr** [HERA-Team/hera_pspec#142]
Calling combine_uvpspec or adding using uvp1 + uvp2 takes very long, Phil suggested that it might be possible to optimize it or something.

**Comment by nkern** [comment]
I'll take a look at this too, b/c i wrote it..

**Comment by nkern** [comment]
Can you give me an example of some `UVPSpec` objects and how many of them you are using? The `test_combine_uvpspec` in `test_uvpspec.py` doesn't take that long at all...

**Comment by philbull** [comment]
This seems to be an issue for UVPSpec objects with lots of blpairs. I did some profiling on an object with 50 blpairs x 200 time samples, and it takes about 9 seconds to run on my computer (which seems like a long time considering the size of the blpairts array index is only 10,000 elements). I'll attach a notebook to demonstrate.

Anyway, the issue seems to be the many calls to the `.index()` method, which seems to be a relatively slow search. We can probably optimise this.

**Comment by philbull** [comment]
[Test_UVPSpec_addition.zip](https://github.com/HERA-Team/hera_pspec/files/2147977/Test_UVPSpec_addition.zip)

**Comment by philbull** [comment]
@duncanjmr and I have been working on several optimisations this afternoon, which should make a significant difference. I'll get those pushed up in the next day or two.

**Comment by philbull** [comment]
OK, see PR #144 for a solution.

**Comment by philbull** [comment]
Solved by PR #144.
