### ISSUE TITLE
Update scalar in hera_pspec

### ISSUE THREAD

**Issue by acliu** [HERA-Team/hera_pspec#19]
Scalar function (with beam^2 etc.) needs to be in the new pspec pipeline.

**Comment by mkolopanis** [comment]
Instead of "correction factors" applied to beam values and such, I've always been a fan of just calculating the omega_p and omega_pp values directly from the beam. Then calculating omega_eff = omega_p**2/omega_pp

It takes a little extra time but feels more transparent to me.

**Comment by mkolopanis** [comment]
this would be contingent on the files having easy access to a beam though

**Comment by SaulAryehKohn** [comment]
These factors are also complicated when it comes to polarization and the full instrumental Jones matrix. Ridhima was looking at the change in power spectrum normalization for a while -- some of it made it in to the final version of Nunhokee et al. 2017. In the present PAPER pipeline, there are different analytic noise curves for each Stokes parameter because of the different beam solid angles associated with each.

**Comment by philbull** [comment]
This was fixed by Adrian a few weeks ago. Closing.
