### ISSUE TITLE
Check OQE window function algebra

### ISSUE THREAD

**Issue by philbull** [HERA-Team/hera_pspec#71]
Now that the power spectrum scalar calculation has been updated, it's possible that the window function calculation in `pspecdata.py` might be wrong. The algebra needs to be revisited.

At the moment, we are intentionally calculating the "wrong" Fisher matrix in OQE (i.e. without the right normalisation/tapering applied), and then correcting for this at the end by applying a renormalisation of the power spectrum when we calculate the scalar. This hasn't been accounted for in the current definition of W, so this needs to be fixed.

**Comment by acliu** [comment]
Checked. The algebra that is being coded up is wrong, because of the whole mess of where we put the taper functions.

Point of Order, Mr. Issue Chairman: The issue is "Check OQE window function algebra", so do I get to close this issue now that I've checked it? Or do I also need to fix it? ;)

(I'm probably the right person to fix this one, but I can't do it right this moment).

**Comment by philbull** [comment]
@acliu Is this fixed by your Decorrelation PR #137?

**Comment by acliu** [comment]
Yes it is.

**Comment by philbull** [comment]
Awesome. We can close it then!
